import os

EXECUTION_TIMEOUT_MS = int(os.getenv("EXECUTION_TIMEOUT_MS", "5000"))
EXECUTION_MEMORY_LIMIT = os.getenv("EXECUTION_MEMORY_LIMIT", "256m")
EXECUTION_CPU_LIMIT = os.getenv("EXECUTION_CPU_LIMIT", "1")
EXECUTION_PIDS_LIMIT = int(os.getenv("EXECUTION_PIDS_LIMIT", "64"))
